mongodb:
  replicaCount: 1
  image:
    repository: mongo
    tag: latest
  service:
    name: mongodb-service
    type: ClusterIP
    port: 27017
  env:
    mongoRootUsername: admin
    mongoRootPassword: password
  additionalLabels:
    environment: dev
    team: backend
  extraEnv:
  - name: LOG_LEVEL
    value: debug
  - name: MAX_CONNECTIONS
    value: "100"
  - name: ENABLE_BACKUPS
    value: "true"

mongoExpress:
  replicaCount: 1
  image:
    repository: mongo-express
    tag: latest
  service:
    name: mongo-express-service
    type: LoadBalancer
    port: 8081
    nodePort: 30001
  env:
    mongoRootUsername: admin
    mongoRootPassword: password
    mongoServer: mongodb-service
  additionalLabels:
    environment: dev
    team: backend
  extraEnv:
  - name: CUSTOM_ENV_VAR1
    value: customValue1
  - name: CUSTOM_ENV_VAR2
    value: customValue2

configMap:
  name: mongodb-configmap
  data:
    database_url: mongodb-service

secret:
  name: mongodb-secret
  data:
    mongoRootUsername: YWRtaW4=
    mongoRootUserPassword: cGFzc3dvcmQ=

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
  - host: mongoexpress.local
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
