apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongoExpress.service.name }}
spec:
  selector:
    app: mongo-express
  type: {{ .Values.mongoExpress.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.mongoExpress.service.port }}
    targetPort: {{ .Values.mongoExpress.service.port }}
    nodePort: {{ .Values.mongoExpress.service.nodePort }}
