apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb
    {{- with .Values.mongodb.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: mongodb
spec:
  replicas: {{ .Values.mongodb.replicaCount }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        {{- with .Values.mongodb.additionalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - image: {{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}
        name: mongodb
        ports:
        - containerPort: {{ .Values.mongodb.service.port }}
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              key: mongo-root-username
              name: {{ .Values.secret.name }}
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mongo-root-password
              name: {{ .Values.secret.name }}
        {{- with .Values.mongodb.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
