apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mongodb-secret
spec:
  encryptedData:
    mongo-root-password: AgAgBXzm7I80IhEs32a6ZVBqbmD9qitX8XjY8vAmDZuqZG+Y0WUXUUe6boB3Fc4C6kR5IUH39o6si66qgAD9LZOPh14Bq0sc6BRHd8w0k1X6+cbtHKAmr3bNw10H3JUT/iCYQ72tpEKJNIvJqyyr9cwhNJ98CHNTjMKgyBkdGI+VcXsUmnTYxfLT7m41DKu+bRifH6Wcv7XQC/AU09xHUy/PcuOrKYwHeyaqy1HMP4X1I/yNQmi52ItYmlgfBqx8/br4k5wQhQg/i9xtHzjTEjAz8bWXjgS36KfCPlyJQYT3Q4GUAtTCA8qHciNmR8R36EJDXZUL0dXxkSTsIb8KFD1rmlIfaWzAtIhAt+1NUE6VNkbyYNh/pJUW6NHYr+VJ6m4DfsA5reEmZ+bdlaBaKUn0dLZvQym9DITWH8N0O9IYFwOHc60g9aRogP2qkStLIGu4VY/BGUxyxGnJ4gY7QRl6RP7uUsCCkJIZhDCYxMjqtuljQ64REmHmHabzvDMwaNXSO+sjFTuweFXh3wajjGAAulifMuZO4yfh+htLZEomLKfZ4iyrNIT3n76POUURsb77GvG2KyAS6QsEG7UuSIUdbohHnU4fwx6QyEe5HCuQOm9I/iFktJXBwJ+nBCNAevOOC8VNAeqigzJeFQPOaN7os4JF6HiaYfS57RultTSBBAuuBWo/Od1V/C0dfkevykLCXuExGHhxRw==
    mongo-root-username: AgAwsZxapBaaflhGLI7HJKLoprJ/AtE92GzSWX2ythbnl6RiL/muTHVlEMNdizGT22tr71xTGxeUkwVlRIopu7Abrpv26DFlIIayhrZPhlFbcB1SKuBdG0Cuyqqova+co+9uUYetyKhzvgYAdF4M9ppQQrXSLWK52JiMlkOLZzJxAAu3PayvDdQ1JX0w7UIXEAOeGxmuhmxb6mDaIjcjVxzhnXkkmWWna/+wuKJmuN60dCbpFFeQKeBrpc7262+Qod3ECbXDj+ipnlx/VpDj1m4bL9GXd22crMWLuNYZIoZowQh+lZbBgcrVy5V0UHlCAxHRtwdtMk3+X9ZJzuIbDR5ypXb2hbinpzPxR/MKVpTKJnZtW2UWh5X4v0EiVyGohHZri+6hKlKEu/W7zrukUQ95YjFHIelJDuAoRr34LC/sFpMjrbXK5qusTWRxRMZdigYphafBAU1UMepD/1OJZXsTPf98px/7N8SlyZoc1hpTVNZVjGiNPCTXqfs5PvYMaGNg9ucUPL6KN9uzLDkAQrisAp/27YZQjvOn+A+BsLdtlNMmy04cHFPDWRgijoP1JZsTuy+Fi9NyQix8G5HbfRymBO6TqXbViC2D9SWfvb+i0SR7uk59q7EhmyjjGfCjPrjWnZfBnMF58AyCXbYGbOwV3xnFjn7ZEUqZ+4TD+a3M4Uhdfd6nSmvYN9WWG75ERIol0ycp3g==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mongodb-secret
    type: Opaque

